/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers:
      | never
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/counter': RouteRecordInfo<
      '/counter',
      '/counter',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/meter-circular/': RouteRecordInfo<
      '/meter-circular/',
      '/meter-circular',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/meter-circular/component': RouteRecordInfo<
      '/meter-circular/component',
      '/meter-circular/component',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/pretext/': RouteRecordInfo<
      '/pretext/',
      '/pretext',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/pretext/component': RouteRecordInfo<
      '/pretext/component',
      '/pretext/component',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'lab/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'lab/pages/counter.vue': {
      routes:
        | '/counter'
      views:
        | never
    }
    'lab/pages/meter-circular/index.vue': {
      routes:
        | '/meter-circular/'
      views:
        | never
    }
    'lab/pages/meter-circular/component.vue': {
      routes:
        | '/meter-circular/component'
      views:
        | never
    }
    'lab/pages/pretext/index.vue': {
      routes:
        | '/pretext/'
      views:
        | never
    }
    'lab/pages/pretext/component.vue': {
      routes:
        | '/pretext/component'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
